export default {
	BACKGROUND_DEEP: '#FFEDE6',
	BACKGROUND_LIGHT: '#FFFFFF',
  MAIN: '#F17D4C',
  SECONDARY_LIGHT: '#CBCBCB',
  SECONDARY_MEDIUM: '#939393',
  SECONDARY_BOLD: '#676767',
  FACEBOOK: '#2A5297',
};